language: python
sudo: false

install:
  - pip install -r requirements.txt

script:
  - py.test --cov=sportsreference --cov-report term-missing tests/
  - pycodestyle sportsreference/ tests/

jobs:
  include:
    - stage: test
      python: 2.7
      dist: trusty
    - stage: test
      python: 3.5
      dist: trusty
    - stage: test
      python: 3.5-dev
      dist: trusty
    - stage: test
      python: 3.6
      dist: trusty
    - stage: test
      python: 3.6-dev
      dist: trusty
    - stage: test
      python: 3.7
      dist: xenial
      sudo: true
    - stage: test
      python: 3.7-dev
      dist: xenial
    - stage: test
      python: 3.8-dev
      dist: xenial
      sudo: true
    - stage: deploy
      dist: xenial
      python: 3.7
      sudo: true
      script: if [[ -z "$TRAVIS_TAG" && $TRAVIS_BRANCH = "patch/"* ]]; then ./dev-version-bump patch; elif [ -z "$TRAVIS_TAG" ]; then ./dev-version-bump minor; fi
      deploy:
          # Steps for master builds
        - provider: pypi
          server: https://test.pypi.org/legacy/
          distributions: sdist bdist_wheel --universal
          user: $PYPI_USERNAME
          password: $PYPI_PASSWORD
          skip_cleanup: true  # Allow version changes to be included
          # Steps for patch fixes
        - provider: pypi
          server: https://test.pypi.org/legacy/
          distributions: sdist bdist_wheel --universal
          user: $PYPI_USERNAME
          password: $PYPI_PASSWORD
          skip_cleanup: true  # Allow version changes to be included
          on:
            all_branches: true
            condition: $TRAVIS_BRANCH =~ ^patch/.*$
          # Steps for tagged releases
        - provider: pypi
          distributions: sdist bdist_wheel --universal
          user: $PYPI_USERNAME
          password: $PYPI_PASSWORD
          skip_cleanup: true  # Allow version changes to be included
          on:
            tags: true
